USE game_db;
SHOW TABLES;

INSERT INTO gamedata (name, publisher, platforms, categories, genres, game_type, price, game_image)
VALUES ("Counter-Strike",	"Valve",	"windows;mac;linux",	"Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/10/header.jpg?t=1528733245"),
("Team Fortress Classic",	"Valve",	"windows;mac;linux",	"Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/20/header.jpg?t=1528732825"),
("Day of Defeat",	"Valve",	"windows;mac;linux",	"Multi-player;Valve Anti-Cheat enabled",	"Action",	"FPS;World War II;Multiplayer",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/30/header.jpg?t=1512413490"),
("Deathmatch Classic",	"Valve",	"windows;mac;linux",	"Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/40/header.jpg?t=1528733362"),
("Half-Life: Opposing Force",	"Valve",	"windows;mac;linux",	"Single-player;Multi-player;Valve Anti-Cheat enabled",	"Action",	"FPS;Action;Sci-fi",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/50/header.jpg?t=1542245736"),
("Ricochet",	"Valve",	"windows;mac;linux",	"Multi-player;Online Multi-Player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/60/header.jpg?t=1528733092"),
("Half-Life",	"Valve",	"windows;mac;linux",	"Single-player;Multi-player;Online Multi-Player;Steam Cloud;Valve Anti-Cheat enabled",	"Action",	"FPS;Classic;Action",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/70/header.jpg?t=1530045175"),
("Counter-Strike: Condition Zero",	"Valve",	"windows;mac;linux",	"Single-player;Multi-player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/80/header.jpg?t=1512411962"),
("Half-Life: Blue Shift",	"Valve",	"windows;mac;linux",	"Single-player",	"Action",	"FPS;Action;Sci-fi",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/130/header.jpg?t=1542159361"),
("Half-Life 2",	"Valve",	"windows;mac;linux",	"Single-player;Steam Achievements;Steam Trading Cards;Captions available;Partial Controller Support;Steam Cloud;Includes Source SDK",	"Action",	"FPS;Action;Sci-fi",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/220/header.jpg?t=1541802014"),
("Counter-Strike: Source",	"Valve",	"windows;mac;linux",	"Multi-player;Cross-Platform Multiplayer;Steam Achievements;Steam Cloud;Valve Anti-Cheat enabled;Stats;Includes Source SDK",	"Action",	"Action;FPS;Multiplayer",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/240/header.jpg?t=1515613564"),
("Half-Life: Source",	"Valve",	"windows;mac;linux",	"Single-player",	"Action",	"FPS;Action;Sci-fi",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/280/header.jpg?t=1530046549"),
("Day of Defeat: Source",	"Valve",	"windows;mac;linux",	"Multi-player;Cross-Platform Multiplayer;Steam Achievements;Steam Trading Cards;Valve Anti-Cheat enabled;Stats;Includes Source SDK",	"Action",	"FPS;World War II;Multiplayer",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/300/header.jpg?t=1512413758"),
("Half-Life 2: Deathmatch",	"Valve",	"windows;mac;linux",	"Multi-player;Valve Anti-Cheat enabled;Includes Source SDK",	"Action",	"Action;FPS;Multiplayer",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/320/header.jpg?t=1512752170"),
("Half-Life 2: Lost Coast",	"Valve",	"windows;mac;linux",	"Single-player;Commentary available",	"Action",	"FPS;Action;Singleplayer",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/340/header.jpg?t=1530046348"),
("Half-Life Deathmatch: Source",	"Valve",	"windows;mac;linux",	"Multi-player;Valve Anti-Cheat enabled",	"Action",	"Action;FPS;Multiplayer",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/360/header.jpg?t=1530046445"),
("Half-Life 2: Episode One",	"Valve",	"windows;mac;linux",	"Single-player;Steam Achievements;Captions available;Partial Controller Support;Steam Cloud;Stats;Includes Source SDK;Commentary available",	"Action",	"FPS;Action;Sci-fi",	5.79,	"https://steamcdn-a.akamaihd.net/steam/apps/380/header.jpg?t=1530046506"),
("Portal",	"Valve",	"windows;mac;linux",	"Single-player;Steam Achievements;Captions available;Partial Controller Support;Includes level editor;Includes Source SDK;Commentary available",	"Action",	"Puzzle;First-Person;Singleplayer",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/400/header.jpg?t=1512752294"),
("Half-Life 2: Episode Two",	"Valve",	"windows;mac;linux",	"Single-player;Steam Achievements;Captions available;Partial Controller Support;Steam Cloud;Stats;Includes Source SDK;Commentary available",	"Action",	"FPS;Action;Sci-fi",	5.79,	"https://steamcdn-a.akamaihd.net/steam/apps/420/header.jpg?t=1530046627"),
("Team Fortress 2",	"Valve",	"windows;mac;linux",	"Multi-player;Cross-Platform Multiplayer;Steam Achievements;Steam Trading Cards;Captions available;Steam Workshop;In-App Purchases;Partial Controller Support;Valve Anti-Cheat enabled;Stats;Includes level editor;Commentary available",	"Action;Free to Play",	"Free to Play;Multiplayer;FPS",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/440/header.jpg?t=1539304875"),
("Left 4 Dead",	"Valve",	"windows;mac",	"Single-player;Multi-player;Co-op;Steam Achievements;Full controller support;Captions available;Steam Cloud;Valve Anti-Cheat enabled;Stats;Steam Leaderboards;Includes Source SDK;Commentary available",	"Action",	"Zombies;Co-op;FPS",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/500/header.jpg?t=1517005754"),
("Left 4 Dead 2",	"Valve",	"windows;mac;linux",	"Single-player;Multi-player;Co-op;Steam Achievements;Full controller support;Steam Trading Cards;Captions available;Steam Workshop;Steam Cloud;Valve Anti-Cheat enabled;Stats;Includes Source SDK;Commentary available",	"Action",	"Zombies;Co-op;FPS",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/550/header.jpg?t=1540300687"),
("Dota 2",	"Valve",	"windows;mac;linux",	"Multi-player;Co-op;Steam Trading Cards;Steam Workshop;SteamVR Collectibles;In-App Purchases;Valve Anti-Cheat enabled",	"Action;Free to Play;Strategy",	"Free to Play;MOBA;Strategy",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/570/header.jpg?t=1554408611"),
("Portal 2",	"Valve",	"windows;mac;linux",	"Single-player;Co-op;Steam Achievements;Full controller support;Steam Trading Cards;Captions available;Steam Workshop;Steam Cloud;Stats;Includes level editor;Commentary available",	"Action;Adventure",	"Puzzle;Co-op;First-Person",	7.19,	"https://steamcdn-a.akamaihd.net/steam/apps/620/header.jpg?t=1512411524"),
("Alien Swarm",	"Valve",	"windows",	"Single-player;Multi-player;Co-op;Steam Achievements;Captions available;Steam Cloud;Stats;Includes level editor",	"Action",	"Free to Play;Co-op;Action",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/630/header.jpg?t=1447353182"),
("Counter-Strike: Global Offensive",	"Valve",	"windows;mac;linux",	"Multi-player;Steam Achievements;Full controller support;Steam Trading Cards;Steam Workshop;In-App Purchases;Valve Anti-Cheat enabled;Stats",	"Action;Free to Play",	"FPS;Multiplayer;Shooter",	0,	"https://steamcdn-a.akamaihd.net/steam/apps/730/header.jpg?t=1554409309"),
("Rag Doll Kung Fu",	"Mark Healey",	"windows",	"Single-player;Multi-player",	"Indie",	"Indie;Fighting;Multiplayer",	5.99,	"https://steamcdn-a.akamaihd.net/steam/apps/1002/header.jpg?t=1447350828"),
("Red Orchestra: Ostfront 41-45",	"Tripwire Interactive",	"windows;mac;linux",	"Multi-player;Steam Achievements;Valve Anti-Cheat enabled",	"Action",	"World War II;Action;FPS",	3.99,	"https://steamcdn-a.akamaihd.net/steam/apps/1200/header.jpg?t=1551467896"),
("Killing Floor",	"Tripwire Interactive",	"windows;mac;linux",	"Single-player;Multi-player;Co-op;Cross-Platform Multiplayer;Steam Achievements;Steam Trading Cards;Steam Workshop;Valve Anti-Cheat enabled;Stats;Includes level editor",	"Action",	"FPS;Zombies;Co-op",	14.99,	"https://steamcdn-a.akamaihd.net/steam/apps/1250/header.jpg?t=1551468074")
;